[small]
part = 1
input = """0123
1234
8765
9876"""
expected = 1

[partial1]
part = 1
input = """...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9"""
expected = 2

[partial2]
part = 1
input = """..90..9
...1.98
...2..7
6543456
765.987
876....
987...."""
expected = 4

[partial3]
part = 1
input = """10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01"""
expected = 3

[big]
part = 1
input = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732"""
expected = 36

[2small]
part = 2
input = """.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9...."""
expected = 3

[2small2]
part = 2
input = """..90..9
...1.98
...2..7
6543456
765.987
876....
987...."""
expected = 13

[2small3]
part = 2
input = """012345
123456
234567
345678
4.6789
56789."""
expected = 227

[2big]
part = 2
input = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732"""
expected = 81
