[test_01]
part = 1
input = """....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#..."""
expected = 41

[test_01b]
part = 1
input = """.#.
#<.
...
"""

[test_02]
part = 2
input = """....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#..."""
expected = 6
