[small1]
part = 1
input = """..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
.........."""
expected = 2

[small2]
part = 1
input = """..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
.........."""
expected = 4

[small3]
part = 1
input = """..........
..........
..........
....a.....
........a.
.....a....
..........
......A...
..........
.........."""
expected = 4


[big]
part = 1
input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
expected = 14

[p2small]
part = 2
input = """T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
.........."""
expected = 9

[p2big]
part = 2
input = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""
expected = 34
