[big]
part = 1
input = """2333133121414131402"""
expected = 1928

[small]
part = 1
input = """12345"""
expected = 60

[reddit]
part = 1
input = """233313312141413140211"""
expected = 2132

[big2]
part = 2
input = """2333133121414131402"""
expected = 2858
